routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Auth
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    # Home
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

    # Profile Management
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'UsersController@edit']);
    Route::patch('profile/update', ['as' => 'profile.update', 'uses' => 'UsersController@update']);

    # Photos Management
    Route::resource('photos', 'PhotosController')->except([
        'edit', 'update', 'destroy'
    ]);
    Route::post('photos/comment', ['as' => 'photos.comment.store', 'uses' => 'PhotoCommentsController@store']);

    Route::get('user/{user}/photos', ['as' => 'user.photos', 'uses' => 'UsersController@photos']);

    # Catalogs Management
    Route::resource('catalogs', 'CatalogsController')->except([
        'edit', 'update', 'destroy'
    ]);
});

resources/views/partials/destroyModal.blade.php
<div aria-hidden="true" role="dialog" tabindex="-1" id="destroyModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                <h4 class="modal-title">{{ trans('modal.destroy.title') }}</h4>
            </div>

            <div class="modal-body form-horizontal">
                <div class="col-sm-12">
                    {{ trans('modal.destroy.body') }}
                </div>

                <div class="col-sm-12">
                    {!! Form::open(['id' => 'destroy-form', 'method' => 'DELETE']) !!}
                        {!! Form::submit(trans('modal.destroy.confirm'), ['class' => 'btn btn-danger col-sm-4']) !!}
                    {!! Form::close() !!}
                    <button data-dismiss="modal" type="button" class="btn btn-default col-sm-4 col-sm-offset-4">
                        {{ trans('modal.destroy.cancel') }}
                    </button>
                </div>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/footer.blade.php
{!! Html::script('assets/js/jquery-2.2.1.min.js') !!}
{!! Html::script('assets/js/bootstrap.min.js') !!}
{!! Html::script('assets/select2-4.0.3/js/select2.min.js') !!}
{!! Html::script('assets/select2-4.0.3/js/i18n/bg.js') !!}
{!! Html::script('assets/datatables/1.10.15/js/jquery.dataTables.min.js') !!}
{{--{!! Html::script('assets/js/fileinput.js') !!}--}}
{!! Html::script('assets/js/jquery.dcjqaccordion.2.7.js') !!}
{!! Html::script('assets/js/jquery.nicescroll.js') !!}
{!! Html::script('assets/js/jquery.scrollTo.min.js') !!}
{!! Html::script('assets/js/scripts.js') !!}
{!! Html::script('assets/js/custom.js') !!}

resources/views/partials/fullActions.blade.php
@if (! isset($noShow))
    <a href="{{ route($module . '.show', [Str::singular($module) => $item]) }}"
       class="btn btn-sm btn-info"
       title="{{ trans('button.view') }}">
        <i class="fa fa-eye"></i>
    </a>
@endif

@if (! isset($noEdit))
    <a href="{{ route($module . '.edit', [Str::singular($module) => $item]) }}"
       class="btn btn-sm btn-warning"
       title="{{ trans('button.edit') }}">
        <i class="fa fa-edit"></i>
    </a>
@endif

@if (! isset($noDestroy))
    <a class="btn btn-sm btn-danger"
       href="#destroyModal" data-toggle="modal"
       title="{{ trans('button.delete') }}"
       data-url="{{ route($module . '.destroy', [Str::singular($module) => $item]) }}">
        <i class="fa fa-trash-o"></i>
    </a>
@endif

resources/views/partials/head.blade.php
<meta charset="UTF-8">
<title>
    Task
</title>

<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}" />

{!! Html::style('assets/css/bootstrap.min.css') !!}
{!! Html::style('assets/css/bootstrap-reset.css') !!}
{!! Html::style('assets/font-awesome-4.7.0/css/font-awesome.min.css') !!}
{!! Html::style('assets/select2-4.0.3/css/select2.min.css') !!}
{!! Html::style('assets/datatables/1.10.15/css/jquery.dataTables.min.css') !!}
{!! Html::style('assets/css/datepicker.css') !!}
{!! Html::style('assets/css/style.css') !!}
{!! Html::style('assets/css/style-responsive.css') !!}
{!! Html::style('assets/css/custom.css') !!}

resources/views/partials/header.blade.php
<header class="header fixed-top clearfix">
    <div class="brand">
        <a href="{{ route('home') }}" class="logo">
            Task
        </a>
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars"></div>
        </div>
    </div>

    <div class="top-nav clearfix">
        <ul class="nav pull-right top-menu">
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="username">{{ auth()->user()->first_name }} {{ auth()->user()->last_name }}</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li><a href="{{ route('profile.edit') }}"><i class="fa fa-user"></i>{{ trans('users/general.profile') }}</a></li>
                    <li>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                            <i class="fa fa-key"></i>{{ trans('users/general.logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
            <!-- user login dropdown end -->
        </ul>
    </div>
</header>

resources/views/partials/initDataTables.blade.php
<script>
    jQuery(function($) {
        let id = 'defaultDataTable';
        {{-- Set custom table id --}}
        @if (isset($tableId))
            id = '{{ $tableId }}';
        @endif

        let table = $('#' + id).DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    url: "{{ request()->url() }}",
                    data: function (data) {
                        data.date = $('#date').val();
                    }
                },
                "order": [
                    @if (isset($orderColumns))
                        @foreach ($orderColumns as $orderColumn => $orderType)
                            [ {{ $orderColumn }}, "{{ $orderType }}" ],
                        @endforeach
                    @endif
                ],
                "aoColumnDefs": [
                    @if (isset($unsearchableColumns))
                        { "bSearchable": false, "aTargets": {!! json_encode((array) $unsearchableColumns) !!} }
                    @endif
                    @if (isset($unsortableColumns))
                        @if (isset($unsearchableColumns)) , @endif
                        { "bSortable": false, "aTargets": {!! json_encode((array) $unsortableColumns) !!} }
                    @endif
                    @if (isset($columnDefs))
                        @foreach ($columnDefs as $class => $targets)
                            { "className": "{{ $class }}", "targets": {!! json_encode((array) $targets) !!} }
                        @endforeach
                    @endif
                ],
                "stateSave": true,
            });

        let param = getParameterByName('search');

        if (param) {
            table.search(param).draw();
        }

        $('div.dataTables_filter input').attr('name', 'dataTablesSearch');

        $('#search-form').on('submit', function(e) {
            e.preventDefault();
            table.draw();
        });
    });
</script>

resources/views/partials/initDatePicker.blade.php
{!! Html::script('assets/js/bootstrap-datepicker.min.js') !!}

<script>
    jQuery(function($) {
        var fieldClass = 'defaultDatePicker';
        {{-- Set custom filed class --}}
        @if (isset($fieldClass))
            fieldClass = '{{ $fieldClass }}';
        @endif

        $('.' + fieldClass).datepicker({
            format: "yyyy-mm-dd",
            autoclose: true,
            language: "{{ App::getLocale() }}",
            weekStart: 1,
            todayHighlight: true,
            todayBtn: "linked",
        });
    });
</script>

resources/views/partials/initSelect2.blade.php
{!! Html::script('assets/select2-4.0.3/js/select2.min.js') !!}

<script>
    jQuery(function($) {
        var fieldClass = 'defaultSelect2';
        {{-- Set custom filed class --}}
        @if (isset($fieldClass))
            fieldClass = '{{ $fieldClass }}';
        @endif

        $('.' + fieldClass).select2({
            language: "{{ App::getLocale() }}",
            placeholder: "{{ trans('general.pleaseChoose') }}",
            width: "100%",
            allowClear: true,
        });
    });
</script>

resources/views/partials/sidebar.blade.php
<aside>
    <div id="sidebar" class="nav-collapse">
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a href="{{ route('home') }}" {!! (request()->routeIs('home') ? 'class="active"' : '') !!}>
                        <i class="fa fa-home"></i>
                        {{ trans('menu.home') }}
                    </a>
                </li>

                <li>
                    <a href="{{ route('photos.index') }}" {!! (request()->is('photos') || request()->is('photos/*') ? 'class="active"' : '') !!}>
                        <i class="fa fa-photo"></i>
                        {{ trans('menu.photos') }}
                    </a>
                </li>

                <li>
                    <a href="{{ route('catalogs.index') }}" {!! (request()->is('catalogs') || request()->is('catalogs/*') ? 'class="active"' : '') !!}>
                        <i class="fa fa-book"></i>
                        {{ trans('menu.catalogs') }}
                    </a>
                </li>
            </ul>
        </div>
    </div>
</aside>