routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Auth
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    # Home
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

    # Profile Management
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'UsersController@edit']);
    Route::patch('profile/update', ['as' => 'profile.update', 'uses' => 'UsersController@update']);

    # Photos Management
    Route::resource('photos', 'PhotosController')->except([
        'edit', 'update', 'destroy'
    ]);
    Route::post('photos/comment', ['as' => 'photos.comment.store', 'uses' => 'PhotoCommentsController@store']);

    Route::get('user/{user}/photos', ['as' => 'user.photos', 'uses' => 'UsersController@photos']);

    # Catalogs Management
    Route::resource('catalogs', 'CatalogsController')->except([
        'edit', 'update', 'destroy'
    ]);
});

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Photo extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'photos';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'image', 'user_id'];

    /**
     * Get photo catalogs.
     */
    public function catalogs(): BelongsToMany
    {
        return $this->belongsToMany(Catalog::class);
    }

    /**
     * Get photo comments.
     */
    public function comments(): HasMany
    {
        return $this->hasMany(PhotoComment::class);
    }

    /**
     * Get the user who owns the photo.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get image filename
     *
     * @return string.
     */
    public function getImageFilenameAttribute(): string
    {
        return $this->id . '-' . $this->image;
    }
}

app/Http/Controllers/PhotosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhotoRequest;
use App\Models\Catalog;
use App\Models\Photo;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class PhotosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $photos = Photo::with('user')->orderBy('id', 'DESC')->get();

        return view('photos.index')
            ->with('photos', $photos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $catalogs = Catalog::where('user_id', auth()->id())->pluck('name', 'id');

        return view('photos.create')
            ->with('catalogs', $catalogs);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PhotoRequest $request
     *
     * @return RedirectResponse
     */
    public function store(PhotoRequest $request): RedirectResponse
    {
        $photoData = [
            'name' => $request->get('name'),
            'image' => $request->file('image')->getClientOriginalName(),
            'user_id' => auth()->id()
        ];

        $photo = Photo::create($photoData);

        $photo->catalogs()->sync($request->get('catalogs'));

        $request->file('image')->storeAs('photos', $photo->imageFilename, 'public');

        return redirect()
            ->route("photos.index")
            ->with('success', trans('message.success.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param Photo $photo
     *
     * @return View
     */
    public function show(Photo $photo): View
    {
        $photo->load('catalogs', 'comments');

        return view('photos.show')
            ->with('photo', $photo);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Photo $photo
     *
     * @return View
     */
    public function edit(Photo $photo): View
    {
        $catalogs = Catalog::where('user_id', auth()->id())->pluck('name', 'id');

        return view('photos.edit')
            ->with('photo', $photo)
            ->with('catalogs', $catalogs);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Photo $photo
     * @param PhotoRequest $request
     *
     * @return RedirectResponse
     */
    public function update(Photo $photo, PhotoRequest $request): RedirectResponse
    {
        $photo->update($request->all());

        return redirect()
            ->route("photos.index")
            ->with('success', trans('message.success.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Photo $photo
     *
     * @return RedirectResponse
     */
    public function destroy(Photo $photo): RedirectResponse
    {
        $photo->delete();

        return redirect()
            ->route("photos.index")
            ->with('success', trans('message.success.delete'));
    }
}

resources/views/photos/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('button.create') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('photos.index') }}">
                    {{ trans('button.back') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                {!! Form::open(['method' => 'POST', 'url' => route('photos.store'), 'files' => true]) !!}
                    @include('photos.form')
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@endsection

resources/views/photos/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('button.edit') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('photos.index') }}">
                    {{ trans('button.back') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                {!! Form::model($photo, ['method' => 'PATCH', 'url' => route('photos.update', $photo), 'files' => true]) !!}
                    @include('photos.form', ['update' => true])
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@endsection

resources/views/photos/form.blade.php
@section('header_styles')
    <link href="{{ asset('assets/select2-4.0.3/css/select2.min.css') }}" rel="stylesheet" type="text/css"/>
@stop

<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', trans('photos/general.name'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {{ Form::text('name', null, ['class' => 'form-control md-input']) }}
    </div>
    <div class="clearfix"></div>
</div>

<div class="form-group {{ $errors->has('image') ? 'has-error' : ''}}">
    {!! Form::label('image', trans('photos/general.image'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {{ Form::file('image', ['class' => 'form-control md-input']) }}
    </div>
    <div class="clearfix"></div>
</div>

<div class="form-group {{ $errors->has('catalogs') ? 'has-error' : ''}}">
    {!! Form::label('catalogs', trans('photos/general.catalogs'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::select('catalogs[]', $catalogs ?? [], null, ['class' => 'form-control defaultSelect2', 'multiple' => 'multiple']) !!}
    </div>
    <div class="clearfix"></div>
</div>

<div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
        @if (isset($update))
            {!! Form::submit(trans('button.edit'), ['class' => 'col-sm-12 btn btn-warning']) !!}
        @else
            {!! Form::submit(trans('button.save'), ['class' => 'col-sm-12 btn btn-success']) !!}
        @endif
    </div>
</div>

@section('footer_scripts')
    @parent

    @include('partials.initSelect2')
@endsection

resources/views/photos/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">{{ trans('menu.photos') }}</h4>
                <a href="{{ route('photos.create') }}" class="pull-right btn btn-success">
                    {{ trans('button.create') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                <table class="table table-hover" id="defaultDataTable">
                    <thead>
                        <tr>
                            <th>{{ trans('photos/general.image') }}</th>
                            <th>{{ trans('photos/general.author') }}</th>
                            <th>{{ trans('general.actions') }}</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($photos as $photo)
                            <tr>
                                <td>
                                    <img src="{{ asset('storage/photos/' . $photo->imageFilename) }}" alt="{{ $photo->name }}" class="preview" style="max-width:100px; max-height:100px;" />
                                </td>
                                <td>
                                    <a href="{{ route('user.photos', $photo->user) }}">
                                        {{ $photo->user->name }}
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route('photos.show', ['photo' => $photo]) }}"
                                       class="btn btn-sm btn-info"
                                       title="{{ trans('button.view') }}">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </section>
    </div>

    @include('partials.destroyModal')
@endsection

resources/views/photos/show.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('menu.photos') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('photos.index') }}">
                    {{ trans('menu.photos') }}
                </a>

                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>{{ trans('photos/general.name') }}</th>
                            <td colspan="2">{{ $photo->name }}</td>
                        </tr>
                        <tr>
                            <th>{{ trans('photos/general.image') }}</th>
                            <td colspan="2">
                                <img src="{{ asset('storage/photos/' . $photo->imageFilename) }}" alt="{{ $photo->name }}" class="preview" style="max-width: 100%" />
                            </td>
                        </tr>
                        <tr>
                            <th>{{ trans('photos/general.catalogs') }}</th>
                            <td colspan="2">
                                @foreach ($photo->catalogs as $catalog)
                                    <span class="label label-default">{{ $catalog->name }}</span>
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th colspan="3">{{ trans('photos/general.comments') }}</th>
                        </tr>
                        <tr>
                            <th>{{ trans('photoComments/general.author') }}</th>
                            <th>{{ trans('photoComments/general.comment') }}</th>
                            <th>{{ trans('photoComments/general.createdAt') }}</th>
                        </tr>
                        @foreach ($photo->comments as $comment)
                            <tr>
                                <td>{{ $comment->user->name }}</td>
                                <td>{{ $comment->comment }}</td>
                                <td>{{ $comment->created_at }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>

                <div class="panel-body">
                    {!! Form::open(['method' => 'POST', 'url' => route('photos.comment.store')]) !!}
                        {!! Form::hidden('photo_id', $photo->id) !!}

                        <div class="form-group {{ $errors->has('comment') ? 'has-error' : ''}}">
                            {!! Form::label('comment', trans('photoComments/general.comment'), ['class' => 'col-sm-3 control-label']) !!}
                            <div class="col-sm-9">
                                {{ Form::textarea('comment', null, ['class' => 'form-control md-input']) }}
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-9 col-sm-offset-3">
                                {!! Form::submit(trans('button.save'), ['class' => 'col-sm-12 btn btn-success']) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </section>
    </div>
@endsection