routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Auth
Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    # Home
    Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

    # Profile Management
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'UsersController@edit']);
    Route::patch('profile/update', ['as' => 'profile.update', 'uses' => 'UsersController@update']);

    # Photos Management
    Route::resource('photos', 'PhotosController')->except([
        'edit', 'update', 'destroy'
    ]);
    Route::post('photos/comment', ['as' => 'photos.comment.store', 'uses' => 'PhotoCommentsController@store']);

    Route::get('user/{user}/photos', ['as' => 'user.photos', 'uses' => 'UsersController@photos']);

    # Catalogs Management
    Route::resource('catalogs', 'CatalogsController')->except([
        'edit', 'update', 'destroy'
    ]);
});

app/Models/Catalog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Catalog extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'catalogs';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'user_id'];

    public static function visibleColumns()
    {
        return [
            '#' => 'catalogs.id',
            'catalogs/general.name' => 'catalogs.name'
        ];
    }

    /**
     * Get photo catalogs.
     */
    public function photos(): BelongsToMany
    {
        return $this->belongsToMany(Photo::class);
    }

    /**
     * Get the user who owns the catalog.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/CatalogsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CatalogRequest;
use App\Models\Catalog;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Yajra\DataTables\DataTables;

class CatalogsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param CatalogRequest $request
     * @param DataTables $dataTables
     *
     * @return JsonResponse | View
     * @throws \Exception
     */
    public function index(CatalogRequest $request, DataTables $dataTables)
    {
        if ($request->wantsJson()) {
            return $this->data($dataTables);
        }

        return view('catalogs.index');
    }

    /**
     * Get data for dataTables
     *
     * @param DataTables $dataTables
     *
     * @return JsonResponse
     * @throws \Exception
     */
    private function data(DataTables $dataTables)
    {
        $catalogs = Catalog::select(array_values(Catalog::visibleColumns()))
            ->where('user_id', auth()->id());

        return $dataTables->eloquent($catalogs)
            ->addColumn('action', function (Catalog $catalog) {
                return view('partials.fullActions', [
                    'module' => 'catalogs',
                    'item' => $catalog,
                    'noEdit' => true,
                    'noDestroy' => true,
                ]);
            })
            ->rawColumns([count(Catalog::visibleColumns())])
            ->make(false);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('catalogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CatalogRequest $request
     *
     * @return RedirectResponse
     */
    public function store(CatalogRequest $request): RedirectResponse
    {
        $catalogData = array_merge($request->all(), ['user_id' => auth()->id()]);

        Catalog::create($catalogData);

        return redirect()
            ->route("catalogs.index")
            ->with('success', trans('message.success.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param Catalog $catalog
     *
     * @return View
     */
    public function show(Catalog $catalog): View
    {
        $catalog->load('photos');

        return view('catalogs.show')
            ->with('catalog', $catalog);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Catalog $catalog
     *
     * @return View
     */
    public function edit(Catalog $catalog): View
    {
        return view('catalogs.edit')
            ->with('catalog', $catalog);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Catalog $catalog
     * @param CatalogRequest $request
     *
     * @return RedirectResponse
     */
    public function update(Catalog $catalog, CatalogRequest $request): RedirectResponse
    {
        $catalog->update($request->all());

        return redirect()
            ->route("catalogs.index")
            ->with('success', trans('message.success.update'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Catalog $catalog
     *
     * @return RedirectResponse
     */
    public function destroy(Catalog $catalog)
    {
        $catalog->delete();

        return redirect()
            ->route("catalogs.index")
            ->with('success', trans('message.success.delete'));
    }
}

resources/views/catalogs/create.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('button.create') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('catalogs.index') }}">
                    {{ trans('button.back') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                {!! Form::open(['method' => 'POST', 'url' => route('catalogs.store')]) !!}
                    @include('catalogs.form')
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@endsection

resources/views/catalogs/edit.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('button.edit') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('catalogs.index') }}">
                    {{ trans('button.back') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                {!! Form::model($catalog, ['method' => 'PATCH', 'url' => route('catalogs.update', $catalog)]) !!}
                    @include('catalogs.form', ['update' => true])
                {!! Form::close() !!}
            </div>
        </section>
    </div>
@endsection

resources/views/catalogs/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    {!! Form::label('name', trans('catalogs/general.name'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {{ Form::text('name', null, ['class' => 'form-control md-input']) }}
    </div>
    <div class="clearfix"></div>
</div>

<div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
        @if (isset($update))
            {!! Form::submit(trans('button.edit'), ['class' => 'col-sm-12 btn btn-warning']) !!}
        @else
            {!! Form::submit(trans('button.save'), ['class' => 'col-sm-12 btn btn-success']) !!}
        @endif
    </div>
</div>

resources/views/catalogs/index.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">{{ trans('menu.catalogs') }}</h4>
                <a href="{{ route('catalogs.create') }}" class="pull-right btn btn-success">
                    {{ trans('button.create') }}
                </a>
                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                <table class="table table-hover" id="defaultDataTable">
                    <thead>
                        <tr>
                            @foreach (\App\Models\Catalog::visibleColumns() as $visibleColumnKey => $visibleColumn)
                                <th>{{ trans($visibleColumnKey) }}</th>
                            @endforeach
                            <th>{{ trans('general.actions') }}</th>
                        </tr>
                    </thead>

                    <tbody>
                    </tbody>
                </table>
            </div>
        </section>
    </div>

    @include('partials.destroyModal')
@endsection

@section('footer_scripts')
    @include('partials.initDataTables')
@endsection

resources/views/catalogs/show.blade.php
@extends('layouts.default')

@section('content')
    <div class="row-fluid">
        <section class="panel">
            <header class="panel-heading">
                <h4 class="pull-left">
                    {{ trans('menu.catalogs') }}
                </h4>
                <a class="pull-right btn btn-primary" href="{{ route('catalogs.index') }}">
                    {{ trans('menu.catalogs') }}
                </a>

                <div class="clearfix"></div>
            </header>

            <div class="panel-body">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>{{ trans('general.id') }}</th>
                            <td>{{ $catalog->id }}</td>
                        </tr>
                        <tr>
                            <th>{{ trans('catalogs/general.name') }}</th>
                            <td>{{ $catalog->name }} </td>
                        </tr>
                        <tr>
                            <th colspan="2">{{ trans('catalogs/general.photos') }}</th>
                        </tr>
                    </tbody>
                </table>

                <div class="container">
                    <div class="row col-md-11">
                        @foreach ($catalog->photos as $photo)
                            <div class="col-md-2" >
                                <div class="thumbnail" style="max-height: 100px">
                                    <img src="{{ asset('storage/photos/' . $photo->imageFilename) }}" alt="{{ $photo->name }}" class="preview" />
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection